config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :meals do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :show]

  get '/search', to: 'pages#search', as: 'search'

  get '/dashboard/:id' , to: "pages#dashboard", as: 'dashboard'

  root to: 'pages#home'
  get '/profile/:id' , to: "pages#profile", as: 'profile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :meal
  validates :date, presence: true
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
  validates :category, presence: true
  validates :price, presence: true
  validates :description, presence: true
  mount_uploader :picture, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :meals# Include default devise modules. Others available are:
  validates :first_name, presence: true
  validates :last_name, presence: true
  mount_uploader :photo, PhotoUploader
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :ischef])
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end


  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :show, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :show, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    redirect_to dashboard_path(current_user)
  end

  def new
    @booking = Booking.new
    @meal = Meal.find(params[:meal_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @meal = Meal.find(params[:meal_id])
    @booking.user_id = current_user.id
    @booking.meal_id = @meal.id
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @meal = @booking.meal
    # @booking.user_id = current_user.id
    # @booking.meal_id = @meal.id
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path(current_user)
  end

  private
  def booking_params
    params.require(:booking).permit(:date, :meal_id, :user_id)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def show
    @meal = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
    @meal.user = current_user
    authorize @meal
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    authorize @meal
    if @meal.save
      redirect_to profile_path(current_user)
    else
      render :new
    end
  end

  def edit
    @meal = Meal.find(params[:id])
    authorize @meal
  end

  def update
    @meal = Meal.find(params[:id])
    authorize @meal
    if @meal.update(meal_params)
      redirect_to meal_path(@meal)
    else
      render :new
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @user = @meal.user
    authorize @meal
    @meal.destroy
    redirect_to profile_path(@user)
  end

  private
  def meal_params
    params.require(:meal).permit(:name, :description, :category, :price, :picture, :picture_cache)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!

  def home
    @meals = Meal.all
  end
#
  def search
    if params[:query].present?
      sql_query = "meals.category ILIKE :query OR meals.name ILIKE :query OR meals.description ILIKE :query OR users.first_name ILIKE :query OR users.last_name ILIKE :query"
      @meals = Meal.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @meals = Meal.all
    end
      @query = params[:query]
  end

  def dashboard

    # @meal = Meal.find(params[:meal_id])
    @user = User.find(params[:id])# find user by ID
    # '/profile/:id', to: pages#profile
    # profile_path(user)
    @bookings = Booking.joins(:meal).where('meals.user_id = ?', current_user.id)
  end

  def profile
    @user = User.find(params[:id])# find user by ID
    # '/profile/:id', to: pages#profile
    # profile_path(user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 col-sm-4 col-md-4 col-sm-offset-4">

      <h2>Make a Booking</h2>

      <%= simple_form_for [@meal, @booking] do |f| %>
      <%= f.input :date, discard_second: true %>
      <%= f.submit "Book", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<%= @booking.date.strftime('%A, %d %b %Y %l:%M %p') %>
<%= link_to "Cancel Booking", booking_path(@booking), method: :delete, data: { confirm: 'Are you sure you want to cancel this booking?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>WokOut</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
  <%= render 'shared/footer' %>
</html>

app/views/meals/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 col-sm-4 col-md-4 col-sm-offset-4">

      <h2>Edit your meal</h2>

      <%= simple_form_for(@meal) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :category, collection: %w(Vietnamese Cantonese Roadkill Dutch Russian German American Canadian) %>
      <%= f.input :price, label: 'Price per person (¥)' %>
      <%= f.input :picture %>
      <%= f.input :picture_cache, as: :hidden %>
      <%= f.submit "Update meal", class: "btn-medium" %>
      <% end %>

    </div>
  </div>
</div>

app/views/meals/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 col-sm-4 col-md-4 col-sm-offset-4">

      <h2>Add a Meal</h2>

      <%= simple_form_for(@meal) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :category, collection: %w(Vietnamese Cantonese Roadkill Dutch Russian German American Canadian) %>
      <%= f.input :price, label: 'Price per person (¥)' %>
      <%= f.input :picture %>
      <%= f.input :picture_cache, as: :hidden %>
      <%= f.submit "add a meal", class: "btn-medium" %>
      <% end %>

    </div>
  </div>
</div>

app/views/meals/show.html.erb
<h1>Meals#show</h1>
<h1><%= @meal.name %></h1>
<h4><%= @meal.description %></h4>
<h4><%= @meal.category %></h4>
<h4><%= @meal.price %></h4>
<p></p>

<% if policy(Meal).edit? %>
<%= link_to "edit", edit_meal_path %>

<% end %>

<%= link_to "delete", meal_path,  method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/pages/_chef_intro.html.erb
 <div style="background-color: white">
          <div class="container" style="position: relative; margin-bottom: 10px;">
            <br>
            <h2 class="featured-home-chefs-title a-bold" style="text-align:center; font-size: 30px; margin-top: 20px">How it works<span></span></h2>
<br>
            <div class="row" style="margin-bottom: 40px;">

              <div class="col-xs-12 col-sm-2">
                <div class="how-it-works-title text-center">
                  <img src="https://image.flaticon.com/icons/svg/749/749998.svg" class="how-it-works-icon" alt="2." width="70">

                </div>
                <div class="how-it-works-content">Select by cuisine, search by chefs &amp; pay securely</div>
              </div>

              <div class="col-xs-12 col-sm-2">
                <div class="how-it-works-title text-center">
                  <img src="https://image.flaticon.com/icons/svg/782/782127.svg" class="how-it-works-icon" alt="3." width="70">
                </div>
                <div class="how-it-works-content">Client makes a reservation</div>
              </div>

              <div class="col-xs-12 col-sm-2">
                <div class="how-it-works-title text-center">
                  <img src="https://image.flaticon.com/icons/svg/649/649395.svg" class="how-it-works-icon" alt="4." width="70">
                </div>
                <div class="how-it-works-content">Chef prepares the ingredients, arrives and starts cooking</div>
              </div>

              <div class="col-xs-12 col-sm-2">
                <div class="how-it-works-title text-center">
                  <img src="https://image.flaticon.com/icons/svg/651/651173.svg" class="how-it-works-icon" alt="5." width="70">
                </div>
                <div class="how-it-works-content">Enjoy great food at home</div>
              </div>

             <div class="col-xs-12 col-sm-2">
                <div class="how-it-works-title text-center">
                  <img src="https://image.flaticon.com/icons/svg/578/578044.svg" class="how-it-works-icon" alt="6." width="70">
                </div>
                <div class="how-it-works-content">Chef returns client's kitchen to its original state</div>
            </div>

            <div class="col-xs-12 col-sm-2">
                <div class="how-it-works-title text-center">
                  <img src="https://image.flaticon.com/icons/svg/651/651191.svg" alt="3." width="70">
                </div>
                <div class="how-it-works-content">Client and chef rate each other</div>
              </div>

            </div>

           <!--  <div class="row" style="margin-bottom:10px;background: #f6f6f6;">
        <div class="col-xs-10 col-md-2 col-md-offset-5 col-xs-offset-1">
          <button class="btn btn-primary btn-xs" style="width: 100%; padding-top:5px; padding-bottom:10px; margin: 40px;font-size:15px;font-weight:700; margin-left: 5px" onclick="$('#indexSearchForm').submit();">Book a Chef<span class="fa fa-hand-pointer-o" aria-hidden="true"></span></button> -->
        </div>
      </div>
        </div>
      </div>

app/views/pages/_footer.html.erb
<footer>
  <div class="copyright">
    <p>&copy 2018 - WokOut</p>
  </div>
  <div class="social">
    <a href="#" class="support">Contact Us</a>
    <a href="#" class="face">f</a>
    <a href="#" class="tweet">t</a>
    <a href="#" class="linked">in</a>
  </div>
</footer>

app/views/pages/dashboard.html.erb
<br>
<div class="tabs">
  <a class="tab active" href="#">
    <h3>4</h3>
    <p> Bookings</p>
  </a>
  <a class="tab" href="#">
    <h3>456</h3>
    <p>Past Bookings</p>
  </a>
  <a class="tab" href="#">
    <h3>189</h3>
    <p>Dishes</p>
  </a>
  <a class="tab" href="#">
    <h3>13</h3>
    <p>Messages</p>
  </a>
</div>

<div class="tabbed-bookings">

  <br>
  <h4>Chefs you have booked:</h4>
  <% @user.bookings.each do |booking| %>
  <h5><%= booking.meal.user.first_name %> <%= booking.meal.user.last_name %></h5>
  <h6>Booked Dish: <%= booking.meal.name %></h6>
  <li>Date: <%= booking.date.strftime('%A %B %e, %l:%M %p') %></li>
  <li><%= link_to "Cancel Booking", booking_path(booking), method: :delete, data: { confirm: 'Are you sure you want to cancel this booking?' } %>
  </li>
  <% end %>

  <br>

  <h4>Upcoming gigs:</h4>
  <% @bookings.each do |booking| %>
  <h5><%= booking.user.first_name %> <%= booking.user.last_name %></h5>
  <h6>Requested Dish: <%= booking.meal.name %></h6>
  <li>Date: <%= booking.date.strftime('%A %B %e, %l:%M %p') %></li>
  <% end %>

</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=74ac7c1aa35dc36f50cc1ac7517c70a7&auto=format&fit=crop&w=1650&q=80');">
  <div class="banner-content">
    <h1>WokOut</h1>
    <p>Eat your homecooked heart out with random strangers you invite to your home</p>
    <div class="wrap">
      <div class="search">
        <%= form_tag search_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
          placeholder: "Search by Chef or Cuisine"
          %>
          <button type="submit" class="searchButton">
            <i class="fa fa-search"></i>
            <% end %>
          </button>
        </div>
      </div>
    </div>
  </div>

  <main class="page-content">
    <%= render 'chef_intro' %>

    <div class="row" style="margin-bottom:40px;margin-top:50px;">
      <div class="col-xs-10 col-md-2 col-md-offset-5 col-xs-offset-1">
        <div class="button-container">
          <%= link_to "Book a Chef", new_user_registration_path, class: "btn btn-medium" %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <% @meals.each do |meal| %>
        <%= link_to profile_path(meal.user) do %>
        <div class="col-xs-12 col-sm-4">
          <div class = "chefcard"> <%= cl_image_tag meal.picture, height: 300, width: 275, crop: :fill%>
            <div class="chef-avatar"><%= cl_image_tag meal.user.photo%></div>
            <div class="card-text-grouping">
              <h4> <%= meal.user.first_name %> <%= meal.user.last_name %> </h4>
              <h5> <%= meal.name %> </h5>
              <h5> <%= meal.price %> RMB | Per Person </h5>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star"></span>
              <div class="specialty"><h6>Specialties: <%= meal.category %></h6></div>
            </div>
          </div>
          <% end %>
        </div>

        <% end %>


      </div>

      <div class="row" style="margin-bottom:40px;margin-top:50px;">
        <div class="col-xs-10 col-md-2 col-md-offset-5 col-xs-offset-1">

        </div>
      </div>

      <!-- <div class="footer-banner" style="background-image: url(<%= image_path("logo-gradient.png") %>); linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%)">
      </div> -->

app/views/pages/profile.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1490645935967-10de6ba17061?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=e0245bb4e87077312cc3d102e68c1efd&auto=format&fit=crop&w=800&q=60');">
  <div class="banner-content">
    <div class="banner-profile">
      <%= cl_image_tag @user.photo, class: "banner-profile" %>
  </div>
  <br>
  <br>
  <br>
  <h2><%= @user.first_name %>
    <br>
    <%= @user.last_name %></a></h2>
  </div>
</div>


<br>



<!-- ..... -->



<div class="card-container">
  <% @user.meals.each do |meal| %>
  <div class="card u-clearfix">
    <div class="card-body">

      <h2 class="card-title"><%= meal.name %></h2>
      <span class="card-description subtle"><%= meal.description %></span>
      <% if user_signed_in? %>
        <div class="card-read"><%= link_to "Book", new_meal_booking_path(meal) %></div>
        <span> <%= link_to "edit", edit_meal_path(meal) %>  <%= link_to "delete", meal_path(meal),  method: :delete, data: { confirm: 'Are you sure you want to delete?' } %></span>
      <% end %>
    </div>

      <%= cl_image_tag meal.picture, class: 'card-media' %>
  </div>
  <div class="card-shadow"></div>
  <br>
  <% end %>
  <br>
</div>



<div class="button-container">
  <%= link_to "add a meal", new_meal_path(@meal), class: "btn btn-medium" %>
</div>

app/views/pages/search.html.erb
<h3>Displaying results for: <%= @query %></h3>
<div class="container">
  <div class="row">
    <div class="col col-xs-12 col-sm-4 col-md-4 col-sm-offset-4">


      <!-- <div class="search"> -->
      <%= form_tag search_path, method: :get do %>
      <%= label_tag "Search again?" %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
        placeholder: ""
        %>
        <% end %>
        <!-- </div> -->

      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">
      <% @meals.each do |meal| %>
      <%= link_to profile_path(meal.user) do %>
      <div class="col-xs-12 col-sm-4">
        <div class = "chefcard"> <%= cl_image_tag meal.picture, height: 300, width: 275, crop: :fill%>
          <div class="chef-avatar"><%= cl_image_tag meal.user.photo%></div>
          <div class="card-text-grouping">
            <h4> <%= meal.user.first_name %> <%= meal.user.last_name %> </h4>
            <h5> <%= meal.name %> </h5>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <div class="specialty"><h6>Specialties: <%= meal.category %></h6></div>
          </div>
        </div>
        <% end %>
      </div>

      <% end %>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
<div class="footer-links">
  <a href="#"><i class="fa fa-github"></i></a>
  <a href="#"><i class="fa fa-instagram"></i></a>
  <a href="#"><i class="fa fa-facebook"></i></a>
  <a href="#"><i class="fa fa-twitter"></i></a>
  <a href="#"><i class="fa fa-pinterest"></i></a>
</div>
<div class="footer-copyright">
  <i class="fa fa-heart"></i>  WokOut
</div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "cutlery-circle.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <!-- <%= link_to "Become a Chef", "#", class: "navbar-wagon-item navbar-wagon-link" %> -->
      <%= link_to "Dashboard", dashboard_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <%= link_to "Messages", class: "navbar-wagon-item navbar-wagon-link" %>
      </div>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Dashboard", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>